### ISSUE TITLE
Why is TARGET_DIR set to muse-bench/MUSE-news_target?

### ISSUE THREAD

**Issue by dong-river** [jaechan-repo/muse_bench#1]
I wonder why the target model for unlearning (aka, TARGET_DIR in the bash command) is muse-bench/MUSE-news_target. In your paper, you said that you started fine-tuning Llama-2 7B. So I assume TARGET_DIR should just be meta-llama/Llama-2-7b-hf? However, I compared these two models and they are different models. Thank you for your response!

**Comment by jaechan-repo** [comment]
An unlearning target refers to a model fine-tuned on both the forget set and the retain set. `meta-llama/Llama-2-7b-hf` has not seen any of those data, so we fine-tune it with those data. The result of the fine-tuning is `muse-bench/MUSE-news_target`, which is the unlearning target.

**Comment by dong-river** [comment]
Thank you for the clarification. So muse-bench/MUSE-news_target is the model after unlearning. Then if I want to reproduce your unlearning results in Table 3, I should change the TARGET_DIR in baselines/scripts/unlearn_books.sh to meta-llama/Llama-2-7b-hf? It's a bit confusing because I thought the script is used to reproduce the unlearning results. Thank you!

**Comment by jaechan-repo** [comment]
Sorry if it was confusing, let me correct it.
- `meta-llama/Llama-2-7b-hf` is a base model's checkpoint. The checkpoint itself means absolutely NOTHING to us, because we don't ever use their weights. We only use their architecture and the tokenizer.
- `muse-bench/MUSE-news_target` is the unlearning target, i.e. a model BEFORE unlearning. This is where the reproduction should begin. You apply the unlearning operations on this model. (Side remark: When I was referring to "fine-tuning" earlier, I was referring to the creation process of this checkpoint, not the unlearning that follows. But this repo doesn't contain that creation script, and the creation itself is just off-the-shelf training, so you can just ignore this process and proceed to unlearning the  `muse-bench/MUSE-news_target` checkpoint that we provide to start off your reproduction.)
- An "unlearned model" is the result of applying unlearning operations to `muse-bench/MUSE-news_target`. This is where the evaluation should be performed.

**Comment by dong-river** [comment]
That makes sense now. Thank you for the clarification.
